### PR TITLE
Gaia variable

### PR DESCRIPTION
**Pull request by abostroem**
This is my initial attempt at creating a database for the Gaia Variable stars. I'm working on downloading the full database but a test ingest file can be found at `/home/saguaro/test_gaiadr3variable_49.tsv`

### CODE REVIEW

**Review by pndaly — COMMENTED** [review]
Looks good. A couple of comments:
 - I use the convention that the index uses the initial letter of the table so "sid serial PRIMARY KEY" should be "gid serial PRIMARY KEY";
 - The index on ra, dec is wrong for Q3C. Instead of a general index it should be "CREATE INDEX ON gaiadr3variable_q3c (q3c_ang2ipix(ra, dec));"

**Review by pndaly — COMMENTED** [review]
Changes in __init__.py are fine.

**Review by pndaly — COMMENTED** [review]
There are lots of places where "sdss12photoz" needs replacing for "gaiadr3variable_q3c".
In the __doc__ section, I usually leave this completely blank until the database is created
and then dump the database table structure to populate the __doc__ section - I hope you
didn't do all that by hand!

Again some references to Sdss12 etc need to be expunged (in the comments mainly).

If you change "sid" -> "gid" (as previously recommended), it also needs changing here.

**Review by pndaly — COMMENTED** [review]
Looks OK. __doc__ section should be left blank and filled in later.

**Review by pndaly — COMMENTED** [review]
ok

**Review by pndaly — COMMENTED** [review]
"from sassy_q3c_models.GAIADR3VARIABLE_q3c_orm import *" should be
from sassy_q3c_models.GaiaDR3variable_q3c_orm import *" or whatever the file is called.

**Comment by abostroem** [comment]
@pndaly I believe I've addressed all of your comments and this is ready for a final review

**Comment by pndaly** [comment]
Mostly looks good: the new import, however, says 'from sassy_q3c_models.GAIADR3variable_q3c_orm import *' ... are you sure that you named the file with (some) CAPITAL letters? If so, I can approve this.

**Comment by abostroem** [comment]
You're right, I misread your comment - fixed

**Pull request merged**
